### ISSUE TITLE
Not able to run app on localhost

### ISSUE THREAD

**Issue by harssh** [stefansenk/spree_multi_tenant#4]
Hi, 
I followed all steps but not able to run app on localhost.
What steps should I follow to do that 

I get 

> RuntimeError in Spree::HomeController#index
> 
> DomainUnknown

**Comment by stefansenk** [comment]
Hi harsshhfs,

The domain that you are hitting in the web browser must match the `domain` field for the corresponding Spree::Tenant, otherwise DomainUnknown is returned.

For example, if you a running via `rails server` which launches on http://0.0.0.0:3000 you could update the tenant's domain to be `0.0.0.0`. Something like:

`Spree::Tenant.first.update_attribute(:domain, '0.0.0.0')`.

Hope that helps.

**Comment by harssh** [comment]
Yep thanks ............
